version: '3.7'
services:
  web:
    image: docker.pkg.github.com/vergissberlin/tagesmutter-peters-de/app
    labels:
      com.centurylinklabs.watchtower.enable: true
    environment:
      - VIRTUAL_HOST=${DOMAINS}
      - VIRTUAL_NETWORK=${NETWORK}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${DOMAINS}
      - LETSENCRYPT_EMAIL=info@andrelademann.de
    restart: on-failure
networks:
  default:
    external:
      name: ${NETWORK}
