version: "3.7"

services:
  app:
    image: nullzueins/tagesmutter-peters
    labels:
      - traefik.enable=true
      - traefik.docker.network=${NETWORK}
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(${DOMAINS})
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=https
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt
    volumes:
      - ./app/:/var/www/html/:ro
    restart: unless-stopped

networks:
  default:
    external:
      name: ${NETWORK}
