name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build . --tag ghcr.io/nullzueins/tagesmutter-peters-de/app:latest

    - name: Push Docker image
      run: |
        docker push ghcr.io/nullzueins/tagesmutter-peters-de/app:latest
